site_name: pynlfff
theme:
  name: null
  custom_dir: 'cinder'
nav:
    - 简介: 'index.md'
    - 准备包: 'pyprepare.md'
#    - 原始数据下载: 'pydownload.md'
#    - 预处理: 'pypreprocess.md'
#    - 计算: 'pycomputer.md'
    - 产品使用: 'pyproduct.md'
    - 图像绘制: 'pyplot.md'
#    - 校验: 'shcheck.md'
#    - 数据支持: 'support.md'

markdown_extensions:
  - admonition


#https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation